CREATE DATABASE CuaHangTrangSuc;
go
USE CuaHangTrangSuc;
go
CREATE TABLE admin (
    AdminID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    USERNAME NVARCHAR(256) NOT NULL,
    PASSWORD NVARCHAR(256) NOT NULL
);
go
CREATE TABLE category (
    CATEGORYID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CATEGORYNAME NVARCHAR(256) NULL
);
go
CREATE TABLE category_attributes (
    CATEGORY_ATTRIBUTEID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CATEGORY_ATTRIBUTENAME NVARCHAR(256) NOT NULL,
    CATEGORYID INT NULL,
    FOREIGN KEY (CATEGORYID) REFERENCES category(CATEGORYID)
);
go
CREATE TABLE category_attributes_detail (
    CATEGORY_ATTRIBUTES_DETAILID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CATEGORY_ATTRIBUTES_DETAILNAME NVARCHAR(256) NOT NULL,
    CATEGORY_ATTRIBUTEID INT NOT NULL,
    FOREIGN KEY (CATEGORY_ATTRIBUTEID) REFERENCES category_attributes(CATEGORY_ATTRIBUTEID)
);
go
CREATE TABLE customer (
    CUSTOMERID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    CUSTOMERNAME NVARCHAR(256) NULL,
    PHONENUMBER NVARCHAR(10) NULL,
    EMAIL NVARCHAR(100) NULL
);
go
CREATE TABLE employee (
    EMPLOYEEID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    FULLNAME NVARCHAR(256) NULL,
    EMAIL NVARCHAR(100) NULL,
    PHONENUMBER NVARCHAR(10) NULL,
    SALARY DECIMAL(10,2) NULL,
    HIRE_DATE DATETIME NULL
);
go
CREATE TABLE orderdetail (
    ORDERDETAILID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    QUANTITY INT NULL,
    TOTAL DECIMAL(10,2) NULL,
    ORDERID INT NOT NULL,
    PRODUCT_SIZEID INT NOT NULL,
    FOREIGN KEY (ORDERID) REFERENCES orders(ORDERID),
    FOREIGN KEY (PRODUCT_SIZEID) REFERENCES product_size(PRODUCT_SIZEID)
);
go
CREATE TABLE orders (
    ORDERID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TOTAL DECIMAL(10,2) NULL,
    CREATEAT DATETIME DEFAULT GETDATE(),
    STATUS INT NULL,
    ADDRESS NVARCHAR(MAX) NULL,
    CUSTOMERID UNIQUEIDENTIFIER NOT NULL,
    SHIPPINGMETHODID INT NOT NULL,
    FOREIGN KEY (CUSTOMERID) REFERENCES customer(CUSTOMERID),
    FOREIGN KEY (SHIPPINGMETHODID) REFERENCES shippingmethods(SHIPPINGMETHODID)
);
go
CREATE TABLE paymentmethods (
    PAYMENTMETHODID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    PAYMENTMETHODNAME NVARCHAR(256) NOT NULL
);
go
CREATE TABLE paymentmethod_order (
    PAYMENTMETHODID INT NOT NULL,
    ORDERID UNIQUEIDENTIFIER NOT NULL,
    STATUS DATETIME NULL,
    PRIMARY KEY (PAYMENTMETHODID, ORDERID),
    FOREIGN KEY (ORDERID) REFERENCES orders(ORDERID),
    FOREIGN KEY (PAYMENTMETHODID) REFERENCES paymentmethods(PAYMENTMETHODID)
);
go
CREATE TABLE products (
    PRODUCTID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PRODUCTNAME NVARCHAR(255) NULL,
    PRICE DECIMAL(10,2) NULL,
    IS_DELETE BIT NULL,
    IMAGE_1 NVARCHAR(255) NULL,
    IMAGE_2 NVARCHAR(255) NULL,
    IMAGE_3 NVARCHAR(255) NULL,
    IMAGE_4 NVARCHAR(255) NULL,
    IMAGE_5 NVARCHAR(255) NULL,
    CATEGORY_ATTRIBUTES_DETAILID INT NOT NULL,
    FOREIGN KEY (CATEGORY_ATTRIBUTES_DETAILID) REFERENCES category_attributes_detail(CATEGORY_ATTRIBUTES_DETAILID)
);
go
CREATE TABLE product_size (
    PRODUCT_SIZEID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PRICE DECIMAL(10,2) NULL,
    QUANTITY INT NULL,
    SIZEID INT NOT NULL,
    PRODUCTID UNIQUEIDENTIFIER NOT NULL,
    UNIQUE (PRODUCTID, SIZEID),
    FOREIGN KEY (SIZEID) REFERENCES size(SIZEID),
    FOREIGN KEY (PRODUCTID) REFERENCES products(PRODUCTID)
);
go
CREATE TABLE purchaseinvoices (
    PURCHASEINVOICEID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TOTAL DECIMAL(15,2) NULL,
    CREATEAT DATETIME NULL,
    STATUS INT NOT NULL,
    SUPPLIERID INT NULL,
    FOREIGN KEY (SUPPLIERID) REFERENCES suppliers(SUPPLIERID)
);
go
CREATE TABLE purchaseinvoice_detail (
    PURCHASEINVOICE_DETAILID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TOTAL DECIMAL(10,2) NULL,
    QUANTITY INT NULL,
    PURCHASEINVOICEID UNIQUEIDENTIFIER NULL,
    PRODUCT_SIZEID UNIQUEIDENTIFIER NULL,
    FOREIGN KEY (PRODUCT_SIZEID) REFERENCES product_size(PRODUCT_SIZEID),
    FOREIGN KEY (PURCHASEINVOICEID) REFERENCES purchaseinvoices(PURCHASEINVOICEID)
);
go
CREATE TABLE shippingmethods (
    SHIPPINGMETHODID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    SHIPPINGMETHODNAME NVARCHAR(256) NOT NULL
);
go
CREATE TABLE size (
    SIZEID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    SizeName NVARCHAR(100) NOT NULL,
    DESCRIPTION_SIZE NVARCHAR(255) NULL
);
go
CREATE TABLE suppliers (
    SUPPLIERID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    SUPPLIERNAME NVARCHAR(255) NULL,
    ADDRESS NVARCHAR(256) NULL,
    PHONUMBER NVARCHAR(12) NULL,
    EMAIL NVARCHAR(100) NULL
);

go
--TRIGGER
CREATE TRIGGER calculate_orderdetail_total
ON orderdetail
INSTEAD OF INSERT
AS
BEGIN
    DECLARE @detail_total DECIMAL(10, 2), @product_sizeid UNIQUEIDENTIFIER, @quantity INT;

    SELECT @product_sizeid = PRODUCT_SIZEID, @quantity = QUANTITY FROM inserted;

    SELECT @detail_total = @quantity * price FROM product_size WHERE PRODUCT_SIZEID = @product_sizeid;

    INSERT INTO orderdetail (ORDERID, PRODUCT_SIZEID, QUANTITY, TOTAL) 
    SELECT ORDERID, @product_sizeid, @quantity, @detail_total FROM inserted;
END;

go
CREATE TRIGGER reduce_stock_after_purchase
ON orderdetail
AFTER INSERT
AS
BEGIN
    DECLARE @product_sizeid UNIQUEIDENTIFIER;
    DECLARE @quantity_purchased INT;

    SELECT @product_sizeid = PRODUCT_SIZEID, @quantity_purchased = QUANTITY
    FROM inserted;

    UPDATE product_size
    SET QUANTITY = QUANTITY - @quantity_purchased
    WHERE PRODUCT_SIZEID = @product_sizeid;
END;

go
CREATE TRIGGER update_order_total
ON orderdetail
AFTER INSERT
AS
BEGIN
    DECLARE @order_id UNIQUEIDENTIFIER;

    SELECT @order_id = ORDERID FROM inserted;

    UPDATE orders
    SET TOTAL = (SELECT SUM(TOTAL) FROM orderdetail WHERE ORDERID = @order_id)
    WHERE ORDERID = @order_id;
END;

go
CREATE TRIGGER update_invoice_total
ON purchaseinvoice_detail
AFTER INSERT
AS
BEGIN
    DECLARE @invoice_id UNIQUEIDENTIFIER;

    SELECT @invoice_id = PURCHASEINVOICEID FROM inserted;

    UPDATE purchaseinvoices
    SET TOTAL = (SELECT SUM(TOTAL * QUANTITY) FROM purchaseinvoice_detail WHERE PURCHASEINVOICEID = @invoice_id)
    WHERE PURCHASEINVOICEID = @invoice_id;
END;


--Dữ liệu

go
INSERT INTO admin (USERNAME, PASSWORD) VALUES ('admin1', 'password1');
INSERT INTO admin (USERNAME, PASSWORD) VALUES ('admin2', 'password2');
INSERT INTO admin (USERNAME, PASSWORD) VALUES ('admin3', 'password3');
go
INSERT INTO category (CATEGORYNAME) VALUES ('Electronics');
INSERT INTO category (CATEGORYNAME) VALUES ('Clothing');
INSERT INTO category (CATEGORYNAME) VALUES ('Books');
go
INSERT INTO category_attributes (CATEGORY_ATTRIBUTENAME, CATEGORYID) VALUES ('Brand', 1);
INSERT INTO category_attributes (CATEGORY_ATTRIBUTENAME, CATEGORYID) VALUES ('Size', 2);
INSERT INTO category_attributes (CATEGORY_ATTRIBUTENAME, CATEGORYID) VALUES ('Author', 3);
go
INSERT INTO category_attributes_detail (CATEGORY_ATTRIBUTES_DETAILNAME, CATEGORY_ATTRIBUTEID) VALUES ('Apple', 1);
INSERT INTO category_attributes_detail (CATEGORY_ATTRIBUTES_DETAILNAME, CATEGORY_ATTRIBUTEID) VALUES ('Nike', 2);
INSERT INTO category_attributes_detail (CATEGORY_ATTRIBUTES_DETAILNAME, CATEGORY_ATTRIBUTEID) VALUES ('J.K. Rowling', 3);
go
INSERT INTO customer (CUSTOMERNAME, PHONENUMBER, EMAIL) VALUES ('John Doe', '0123456789', 'john.doe@example.com');
INSERT INTO customer (CUSTOMERNAME, PHONENUMBER, EMAIL) VALUES ('Jane Smith', '0987654321', 'jane.smith@example.com');
INSERT INTO customer (CUSTOMERNAME, PHONENUMBER, EMAIL) VALUES ('Sam Wilson', '1234567890', 'sam.wilson@example.com');
go
INSERT INTO employee (FULLNAME, EMAIL, PHONENUMBER, SALARY, HIRE_DATE) VALUES ('Alice Johnson', 'alice.j@example.com', '1112233445', 50000, GETDATE());
INSERT INTO employee (FULLNAME, EMAIL, PHONENUMBER, SALARY, HIRE_DATE) VALUES ('Bob Brown', 'bob.b@example.com', '2223344556', 60000, GETDATE());
INSERT INTO employee (FULLNAME, EMAIL, PHONENUMBER, SALARY, HIRE_DATE) VALUES ('Charlie Black', 'charlie.b@example.com', '3334455667', 55000, GETDATE());
go
INSERT INTO orders (ORDERID, TOTAL, CREATEAT, STATUS, ADDRESS, CUSTOMERID, SHIPPINGMETHODID) VALUES (NEWID(), 100.00, GETDATE(), 1, '123 Main St', NEWID(), 1);
INSERT INTO orders (ORDERID, TOTAL, CREATEAT, STATUS, ADDRESS, CUSTOMERID, SHIPPINGMETHODID) VALUES (NEWID(), 150.50, GETDATE(), 1, '456 Side St', NEWID(), 2);
INSERT INTO orders (ORDERID, TOTAL, CREATEAT, STATUS, ADDRESS, CUSTOMERID, SHIPPINGMETHODID) VALUES (NEWID(), 200.75, GETDATE(), 1, '789 Back St', NEWID(), 3);
go
INSERT INTO paymentmethods (PAYMENTMETHODNAME) VALUES ('Credit Card');
INSERT INTO paymentmethods (PAYMENTMETHODNAME) VALUES ('PayPal');
INSERT INTO paymentmethods (PAYMENTMETHODNAME) VALUES ('Bank Transfer');
go
INSERT INTO products (PRODUCTID, PRODUCTNAME, PRICE, IS_DELETE, IMAGE_1, CATEGORY_ATTRIBUTES_DETAILID) VALUES (NEWID(), 'iPhone 12', 799.99, 0, 'image1.jpg', 1);
INSERT INTO products (PRODUCTID, PRODUCTNAME, PRICE, IS_DELETE, IMAGE_1, CATEGORY_ATTRIBUTES_DETAILID) VALUES (NEWID(), 'Nike Shoes', 149.99, 0, 'image2.jpg', 2);
INSERT INTO products (PRODUCTID, PRODUCTNAME, PRICE, IS_DELETE, IMAGE_1, CATEGORY_ATTRIBUTES_DETAILID) VALUES (NEWID(), 'Harry Potter', 39.99, 0, 'image3.jpg', 3);
go
INSERT INTO product_size (PRODUCT_SIZEID, PRICE, QUANTITY, SIZEID, PRODUCTID) VALUES (NEWID(), 799.99, 10, 1, NEWID());
INSERT INTO product_size (PRODUCT_SIZEID, PRICE, QUANTITY, SIZEID, PRODUCTID) VALUES (NEWID(), 149.99, 5, 2, NEWID());
INSERT INTO product_size (PRODUCT_SIZEID, PRICE, QUANTITY, SIZEID, PRODUCTID) VALUES (NEWID(), 39.99, 15, 3, NEWID());
go
INSERT INTO purchaseinvoices (PURCHASEINVOICEID, TOTAL, CREATEAT, STATUS, SUPPLIERID) VALUES (NEWID(), 500.00, GETDATE(), 1, 1);
INSERT INTO purchaseinvoices (PURCHASEINVOICEID, TOTAL, CREATEAT, STATUS, SUPPLIERID) VALUES (NEWID(), 750.00, GETDATE(), 1, 2);
INSERT INTO purchaseinvoices (PURCHASEINVOICEID, TOTAL, CREATEAT, STATUS, SUPPLIERID) VALUES (NEWID(), 1200.00, GETDATE(), 1, 3);
go
INSERT INTO purchaseinvoice_detail (PURCHASEINVOICE_DETAILID, TOTAL, QUANTITY, PURCHASEINVOICEID, PRODUCT_SIZEID) VALUES (NEWID(), 500.00, 5, NEWID(), NEWID());
INSERT INTO purchaseinvoice_detail (PURCHASEINVOICE_DETAILID, TOTAL, QUANTITY, PURCHASEINVOICEID, PRODUCT_SIZEID) VALUES (NEWID(), 750.00, 3, NEWID(), NEWID());
INSERT INTO purchaseinvoice_detail (PURCHASEINVOICE_DETAILID, TOTAL, QUANTITY, PURCHASEINVOICEID, PRODUCT_SIZEID) VALUES (NEWID(), 1200.00, 2, NEWID(), NEWID());
go
INSERT INTO shippingmethods (SHIPPINGMETHODNAME) VALUES ('Standard Shipping');
INSERT INTO shippingmethods (SHIPPINGMETHODNAME) VALUES ('Express Shipping');
INSERT INTO shippingmethods (SHIPPINGMETHODNAME) VALUES ('Overnight Shipping');
go
INSERT INTO size (SizeName, DESCRIPTION_SIZE) VALUES ('Small', 'Small size');
INSERT INTO size (SizeName, DESCRIPTION_SIZE) VALUES ('Medium', 'Medium size');
INSERT INTO size (SizeName, DESCRIPTION_SIZE) VALUES ('Large', 'Large size');
go
INSERT INTO suppliers (SUPPLIERNAME, ADDRESS, PHONUMBER, EMAIL) VALUES ('Supplier A', 'Address A', '1234567890', 'supplierA@example.com');
INSERT INTO suppliers (SUPPLIERNAME, ADDRESS, PHONUMBER, EMAIL) VALUES ('Supplier B', 'Address B', '0987654321', 'supplierB@example.com');
INSERT INTO suppliers (SUPPLIERNAME, ADDRESS, PHONUMBER, EMAIL) VALUES ('Supplier C', 'Address C', '1112233445', 'supplierC@example.com');
go
